export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const DELETE_INFO = 'DELETE_INFO';
export const CANCEL_EDIT_USER = 'CANCEL_EDIT_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';



